services:
    _defaults:
        autowire: true
        autoconfigure: true

    Webwerkwien\ContaoAiCoreBundle\:
        resource: ../src
        exclude: ../src/{ContaoManager,ContaoAiCoreBundle.php}

    Webwerkwien\ContaoAiCoreBundle\Command\FolderCreateCommand:
        arguments:
            $projectDir: '%kernel.project_dir%'

    Webwerkwien\ContaoAiCoreBundle\Command\FileProcessCommand:
        arguments:
            $projectDir: '%kernel.project_dir%'

    Webwerkwien\ContaoAiCoreBundle\Command\FileReadCommand:
        arguments:
            $projectDir: '%kernel.project_dir%'

    Webwerkwien\ContaoAiCoreBundle\Command\FileWriteCommand:
        arguments:
            $projectDir: '%kernel.project_dir%'

    Webwerkwien\ContaoAiCoreBundle\Command\TemplateListCommand:
        arguments:
            $projectDir: '%kernel.project_dir%'

    Webwerkwien\ContaoAiCoreBundle\Command\TemplateReadCommand:
        arguments:
            $projectDir: '%kernel.project_dir%'

    Webwerkwien\ContaoAiCoreBundle\Command\TemplateWriteCommand:
        arguments:
            $projectDir: '%kernel.project_dir%'
